server:
  port: 8088

  spring:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/springboot
      username: root
      password: mysql
      driver-class-name: com.mysql.vj.jdbc.Driver


mybatis:
  type-aliases-package: com.example.springbootmybatis.entity
  mapper-locations: mapper/**/*.xml

